title: Playstation is better..
author: Todd Reinier
email: toddreinier7@gmail.com 
theme: minima
description: > # Playstation is better I think than xbox 
and remote play alone makes it better
  
  

# social links

github_username:  tihien14

show_excerpts: false
